// src/lib/types.ts
export type Product = {
  id: string;
  name: string;
  description: string;
  stock: number;
  photoUrl?: string; // Base64 encoding of image for local storage
  createdAt: string;
  updatedAt: string;
};

export type ShopeePurchaseMethod = 'Online Payment' | 'COD' | 'Shopee Pay Later' | 'Instant';
export type ShopeeOrderStatus = 'Shipped' | 'Delivered' | 'Returned';
export type ShopeeDeliveryMethod = 'Shopee Xpress' | 'J&T Express' | 'JNE' | 'SiCepat' | 'Anteraja' | 'Lainnya';
export type ShopeeReturnStatus =
  | 'Barang Bagus'
  | 'Barang Rusak - Menunggu Shopee'
  | 'Barang Rusak - Dikompensasi'
  | 'Barang Rusak - Ditolak';

export type ShopeeOrderItem = {
  id: string;
  productId: string;
  quantity: number;
};

export type ShopeeSale = {
  id: string;
  orderId: string;
  deliveryId: string;
  items: ShopeeOrderItem[];
  price: number; // Estimated total receipt amount for the order
  finalReceiptAmount: number | null; // Confirmed final amount after Shopee delivery
  receivableAmount: number; // Generated by Supabase from status + final/estimated receipt amount
  deliveryMethod: ShopeeDeliveryMethod;
  purchaseMethod: ShopeePurchaseMethod;
  note: string;
  status: ShopeeOrderStatus;
  date: string;
  createdAt: string;
};

export type ShopeeReturnCase = {
  id: string;
  shopeeOrderId: string;
  returnStatus: ShopeeReturnStatus;
  compensationAmount: number;
  note: string;
  order: ShopeeSale;
  createdAt: string;
  updatedAt: string;
};

export type StorePurchaseMethod = 'Cash' | 'Credit' | 'Transfer';

export type StoreSale = {
  id: string;
  deliveryId: string;
  productId: string;
  quantity: number;
  price: number;
  purchaseMethod: StorePurchaseMethod;
  date: string; // The date of occurrence
  deadline?: string; // Optional if purchaseMethod is 'Credit'
  createdAt: string;
};
